name: CI

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: yarn install
            - run: yarn run build
            - run: yarn run test
              env:
                  CI: true
            - run: yarn publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
